### ISSUE TITLE
getting error updating the realtime candle

### ISSUE THREAD

**Issue by pelife** [hackingthemarkets/gridbot-websockets#1]
sometimes I am getting this error while I tries to update realtine candle:

this gridbot.js line 147 is this:

candleSeries.update(currentBar);

lightweight-charts.standalone.production.js:7 Uncaught Error: Cannot update oldest data, last time=1648128180, new time=1648128120
    at t.hM (lightweight-charts.standalone.production.js:7:142348)
    at t.dM (lightweight-charts.standalone.production.js:7:155747)
    at i.t.update (lightweight-charts.standalone.production.js:7:145777)
    at WebSocket.socket.onmessage (gridbot.js:147:26)
t.hM @ lightweight-charts.standalone.production.js:7
t.dM @ lightweight-charts.standalone.production.js:7
t.update @ lightweight-charts.standalone.production.js:7
socket.onmessage @ gridbot.js:147

**Comment by ghacosta** [comment]
Yeap, I'm getting same error but it is not consistent, it is not happening everytime.

**Comment by jakelowen** [comment]
Same. Seems related to https://github.com/tradingview/lightweight-charts/issues/592

**Comment by kandarpgautam** [comment]
I am getting the same issue. How I expect it to work is, that if I have the same time for a bar that was previously rendered, then the new data should update the old bar.

**Comment by 0x1af2aec8f957** [comment]
```ts
candlestickSeries.update(item, true)
```
