### ISSUE TITLE
is the code operational?

### ISSUE THREAD

**Issue by virgiliofilhos** [hackingthemarkets/gridbot-websockets#4]
when i execute show me:
`submitting market limit buy order at -1.99992679
Traceback (most recent call last):
  File "/home/filho/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 633, in fetch
    response.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/order

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/filho/btc/gridbot-websockets/gridbot.py", line 18, in <module>
    order = exchange.create_limit_buy_order(config.SYMBOL, config.POSITION_SIZE, price)
  File "/home/filho/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 2864, in create_limit_buy_order
    return self.create_order(symbol, 'limit', 'buy', amount, price, params)
  File "/home/filho/.local/lib/python3.10/site-packages/ccxt/binance.py", line 2855, in create_order
    response = getattr(self, method)(self.extend(request, params))
  File "/home/filho/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 497, in inner
    return entry(_self, **inner_kwargs)
  File "/home/filho/.local/lib/python3.10/site-packages/ccxt/binance.py", line 5318, in request
    response = self.fetch2(path, api, method, params, headers, body, config, context)
  File "/home/filho/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 541, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/filho/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 649, in fetch
    skip_further_error_handling = self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/home/filho/.local/lib/python3.10/site-packages/ccxt/binance.py", line 5296, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], error, feedback)
  File "/home/filho/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 2724, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.BadRequest: binance {"code":-1100,"msg":"Illegal characters found in parameter 'price'; legal range is '^([0-9]{1,20})(\\.[0-9]{1,20})?$'."}
`

the quantity is represented by the "POSITION_SIZE" config entry?

I can't identify the reason for the error.
Can you help me?
I use binance for testing. (yes I already changed it to ccxt.binance )

**Comment by ketzah** [comment]
I'm not the author and not sure it's being maintained. 

the "POSITION_SIZE" config entry is correlated to the base coin asset.
